### PR TITLE
mostly testing plans

### PR DESCRIPTION
**Pull request by mootpt**

### CODE REVIEW

**Comment by mootpt** [comment]
atlantis plan

**Comment by mootpt** [comment]
atlantis plan

**Comment by mootpt** [comment]
atlantis plan

**Comment by mootpt** [comment]
atlantis plan

**Comment by weekendops-atlantis** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_route53_record.matrix-ack-zone will be created
+ resource "aws_route53_record" "matrix-ack-zone" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "ack.zone"
      + records         = [
          + "127.0.0.1",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = "Z3QYCI7E2TAT9Q"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.weekendops.com/lock?id=ackzone%252Finfra%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by weekendops-atlantis** [comment]
**Warning**: The plan for dir: `terraform` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by mootpt** [comment]
atlantis plan

**Comment by weekendops-atlantis** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # aws_route53_record.matrix-ack-zone will be created
+ resource "aws_route53_record" "matrix-ack-zone" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "ack.zone"
      + records         = [
          + "127.0.0.1",
        ]
      + ttl             = 300
      + type            = "A"
      + zone_id         = "Z3QYCI7E2TAT9Q"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.weekendops.com/lock?id=ackzone%252Finfra%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by weekendops-atlantis** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `default`

**Pull request closed without merging**
